import { type NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { getPsAuth } from "~/utils/psAuth";
import { api } from "~/utils/api";
import type { GetServerSideProps } from "next";
import { exchangeNpssoForCode, exchangeCodeForAccessToken, makeUniversalSearch } from "psn-api";

const Home: NextPage = ({ authorization }) => {
  const [ username, setUsername ] = useState("");
  
  const getPsUser = async () => {
    const res = await makeUniversalSearch(
      authorization,
      username,
      "SocialAllAccounts"
    )
  }
  console.log(getPsUser())
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ()=> {
  const accessCode = await exchangeNpssoForCode(process.env.NPSSO)
  const authorization = await exchangeCodeForAccessToken(accessCode);
  return {
    props: {
      authorization
    }
  }
}

export default Home;

