import { type NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";


const Home: NextPage = () => {
  const [ username, setUsername ] = useState("iamthewombraider");
  const { data: user } = api.user.getUser.useQuery({text: username});
  console.log(user)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        
      </main>
    </>
  );
};

export default Home;

